"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowRight, CheckCircle2, ImagePlus, X } from "lucide-react";
import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";

type Values = {
  senderName: string;
  senderPhone: string;
  receiverName: string;
  receiverPhone: string;
  deliveryAddress: string;
  deliveryZone: string;
  pickupMethod: "SENDER_DROP_OFF" | "RIDER_PICKUP";
  pickupAddress: string;
  pickupInstructions: string;
  packageDescription: string;
  quantity: string;
  notes: string;
  paymentMethod: "ALREADY_PAID" | "PAYMENT_ON_DELIVERY";
  orderAmount: string;
};
const initialValues: Values = {
  senderName: "",
  senderPhone: "",
  receiverName: "",
  receiverPhone: "",
  deliveryAddress: "",
  deliveryZone: "",
  pickupMethod: "SENDER_DROP_OFF",
  pickupAddress: "",
  pickupInstructions: "",
  packageDescription: "",
  quantity: "1",
  notes: "",
  paymentMethod: "PAYMENT_ON_DELIVERY",
  orderAmount: "",
};
const allowedImageExtensions = new Set(["png", "jpeg", "jpg", "webp"]);
const allowedImageTypes = new Set(["image/png", "image/jpeg", "image/webp"]);

export default function CreateOrderPage() {
  const zones = useQuery({
    queryKey: ["delivery-zones"],
    queryFn: api.getDeliveryZones,
  });
  const [values, setValues] = useState(initialValues);
  const [images, setImages] = useState<{ file: File; url: string }[]>([]);
  const [imageError, setImageError] = useState("");
  const [created, setCreated] = useState<Awaited<
    ReturnType<typeof api.createOrder>
  > | null>(null);
  const mutation = useMutation({
    mutationFn: () =>
      api.createOrder({
        ...values,
        quantity: Number(values.quantity),
        orderAmount: values.orderAmount
          ? Number(values.orderAmount)
          : undefined,
        images: images.map((image) => ({
          name: image.file.name,
          url: image.url,
        })),
      }),
    onSuccess: setCreated,
  });
  const set = <K extends keyof Values>(key: K, value: Values[K]) =>
    setValues((current) => ({ ...current, [key]: value }));
  function chooseImages(event: React.ChangeEvent<HTMLInputElement>) {
    const selected = Array.from(event.target.files || []);
    const invalid = selected.filter((file) => {
      const extension = file.name.split(".").pop()?.toLowerCase();
      return (
        !extension ||
        !allowedImageExtensions.has(extension) ||
        (file.type && !allowedImageTypes.has(file.type))
      );
    });
    if (invalid.length > 0) {
      setImageError("Only PNG, JPEG, JPG, and WebP images are allowed.");
    } else {
      setImageError("");
    }
    const valid = selected.filter((file) => !invalid.includes(file)).slice(0, 5);
    setImages(
      valid.map((file) => ({ file, url: URL.createObjectURL(file) })),
    );
    event.target.value = "";
  }
  if (created)
    return (
      <main className="public-page">
        <div className="public-card success-card">
          <CheckCircle2 size={40} color="#2d9862" />
          <h1>Order Created Successfully</h1>
          <div className="code-box">
            <span>Order ID</span>
            <strong>{created.orderId || "Generated by backend"}</strong>
          </div>
          <p className="subtext">
            Status: Pending Approval. The owner will review your order before
            delivery begins.
          </p>
          <Link href="/create-order" className="button button-primary">
            Create another order
          </Link>
        </div>
      </main>
    );
  return (
    <main className="public-page">
      <div className="public-card">
        <header className="public-header">
          <p className="eyebrow">Shagil delivery</p>
          <h1>Create Your Delivery</h1>
          <p className="subtext">
            Complete the order details. No account or special link is required.
          </p>
        </header>
        <form
          className="public-form"
          onSubmit={(event) => {
            event.preventDefault();
            mutation.mutate();
          }}
        >
          <Section title="1. Sender information">
            <div className="form-grid">
              <Field
                label="Sender / business name"
                value={values.senderName}
                required
                onChange={(v) => set("senderName", v)}
              />
              <Field
                label="Sender phone number"
                type="tel"
                required
                value={values.senderPhone}
                onChange={(v) => set("senderPhone", v)}
              />
            </div>
          </Section>
          <Section title="2. Receiver information">
            <div className="form-grid">
              <Field
                label="Receiver name"
                required
                value={values.receiverName}
                onChange={(v) => set("receiverName", v)}
              />
              <Field
                label="Receiver phone number"
                type="tel"
                required
                value={values.receiverPhone}
                onChange={(v) => set("receiverPhone", v)}
              />
              <Field
                label="Receiver delivery address"
                required
                value={values.deliveryAddress}
                onChange={(v) => set("deliveryAddress", v)}
              />
            </div>
          </Section>
          <Section title="3. Pickup">
            <select
              className="select"
              value={values.pickupMethod}
              onChange={(e) =>
                set("pickupMethod", e.target.value as Values["pickupMethod"])
              }
            >
              <option value="SENDER_DROP_OFF">
                Sender drops package at company office
              </option>
              <option value="RIDER_PICKUP">
                Rider picks package from sender
              </option>
            </select>
            {values.pickupMethod === "RIDER_PICKUP" ? (
              <div className="form-grid public-followup">
                <Field
                  label="Pickup address"
                  required
                  value={values.pickupAddress}
                  onChange={(v) => set("pickupAddress", v)}
                />
                <Field
                  label="Pickup instructions"
                  value={values.pickupInstructions}
                  onChange={(v) => set("pickupInstructions", v)}
                />
              </div>
            ) : (
              <p className="form-hint">
                After submitting, bring the package to the company office for
                receiving.
              </p>
            )}
          </Section>
          <Section title="4. Product">
            <div className="form-grid">
              <Field
                label="Product description"
                required
                value={values.packageDescription}
                onChange={(v) => set("packageDescription", v)}
              />
              <Field
                label="Quantity"
                type="number"
                required
                value={values.quantity}
                onChange={(v) => set("quantity", v)}
              />
              <Field
                label="Notes"
                value={values.notes}
                onChange={(v) => set("notes", v)}
              />
            </div>
            <label className="upload-field">
              <ImagePlus size={18} /> Add product images
              <input
                type="file"
                accept=".png,.jpeg,.jpg,.webp,image/png,image/jpeg,image/webp"
                multiple
                onChange={chooseImages}
              />
            </label>
            {imageError && <p className="form-error" role="alert">{imageError}</p>}
            {images.length > 0 && (
              <div className="upload-previews">
                {images.map((image, index) => (
                  <div key={image.url}>
                    <Image
                      src={image.url}
                      alt={image.file.name}
                      width={160}
                      height={160}
                    />
                    <button
                      type="button"
                      className="icon-button"
                      aria-label={`Remove ${image.file.name}`}
                      onClick={() =>
                        setImages((current) =>
                          current.filter((_, itemIndex) => itemIndex !== index),
                        )
                      }
                    >
                      <X size={15} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </Section>
          <Section title="5. Delivery">
            <div className="field">
              <label htmlFor="create-zone">Lagos delivery zone</label>
              <select
                className="select"
                id="create-zone"
                required
                value={values.deliveryZone}
                onChange={(e) => set("deliveryZone", e.target.value)}
              >
                <option value="">Select a zone</option>
                {(zones.data || [])
                  .filter((zone) => zone.active)
                  .map((zone) => (
                    <option key={zone.id} value={zone.name}>
                      {zone.name}
                    </option>
                  ))}
              </select>
            </div>
          </Section>
          <Section title="6. Payment">
            <select
              className="select"
              value={values.paymentMethod}
              onChange={(e) =>
                set("paymentMethod", e.target.value as Values["paymentMethod"])
              }
            >
              <option value="ALREADY_PAID">Already paid</option>
              <option value="PAYMENT_ON_DELIVERY">Payment on delivery</option>
            </select>
            {values.paymentMethod === "PAYMENT_ON_DELIVERY" && (
              <Field
                label="Order / product amount"
                type="number"
                required
                value={values.orderAmount}
                onChange={(v) => set("orderAmount", v)}
              />
            )}
            <p className="form-hint">
              Delivery fee and final total are calculated by the backend.
            </p>
          </Section>
          {mutation.isError && (
            <p className="form-error" role="alert">
              We could not create this order. Check the details and try again.
            </p>
          )}
          <button
            className="button button-primary button-full"
            disabled={mutation.isPending}
          >
            {mutation.isPending ? (
              "Creating order..."
            ) : (
              <>
                Create Order <ArrowRight size={17} />
              </>
            )}
          </button>
        </form>
        <p className="public-foot">
          <Link href="/login">Staff sign in</Link>
        </p>
      </div>
    </main>
  );
}
function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <fieldset>
      <legend>{title}</legend>
      {children}
    </fieldset>
  );
}
function Field({
  label,
  value,
  onChange,
  type = "text",
  required = false,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
  type?: string;
  required?: boolean;
}) {
  return (
    <div className="field">
      <label>{label}</label>
      <input
        className="input"
        required={required}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
      />
    </div>
  );
}
