"use client";

import Link from "next/link";
import { CheckCircle2, Copy, ArrowLeft } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/layout/app-shell";
import { useRoleRedirect } from "@/components/auth/auth-provider";
import { api } from "@/lib/api";
import { LoadingState } from "@/components/ui/primitives";
import { WhatsAppButton } from "@/components/orders/whatsapp-button";

const schema = z.object({ customerName: z.string().min(2, "Enter the customer name"), customerPhone: z.string().min(7, "Enter a valid phone number"), orderDetails: z.string().min(2, "Add what was ordered"), deliveryAddress: z.string().min(5, "Enter the delivery address"), amount: z.string().optional(), assignedRiderId: z.string().optional() });
type FormValues = z.infer<typeof schema>;
export default function NewOrderPage() { const { user, isLoading } = useRoleRedirect("OWNER"); const riders = useQuery({ queryKey: ["riders"], queryFn: api.getRiders, enabled: Boolean(user) }); const queryClient = useQueryClient(); const [created, setCreated] = useState<Awaited<ReturnType<typeof api.createOrder>> | null>(null); const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { customerName: "", customerPhone: "", orderDetails: "", deliveryAddress: "", amount: "", assignedRiderId: "" } }); const mutation = useMutation({ mutationFn: (values: FormValues) => api.createOrder({ ...values, amount: values.amount ? Number(values.amount) : undefined }), onSuccess: order => { setCreated(order); queryClient.invalidateQueries({ queryKey: ["orders"] }); } }); if (isLoading || !user) return <LoadingState />;
  if (created) return <AppShell role="OWNER"><div className="page"><Link href="/owner/orders" className="back-link"><ArrowLeft size={16} /> Back to orders</Link><div className="success-card success-order"><CheckCircle2 size={35} color="#2d9862" /><h2>Order created successfully</h2><p className="subtext">Share these details with {created.customerName}.</p><div className="code-box"><span>Order ID</span><strong>{created.orderId || created.id}</strong><button className="icon-button light" aria-label="Copy order ID" onClick={() => navigator.clipboard.writeText(created.orderId || created.id)}><Copy size={17} /></button></div><div className="code-box"><span>Delivery code</span><strong>{created.deliveryCode || "—"}</strong><button className="icon-button light" aria-label="Copy delivery code" onClick={() => navigator.clipboard.writeText(created.deliveryCode || "")}><Copy size={17} /></button></div><div className="inline-actions"><WhatsAppButton phone={created.customerPhone} customerName={created.customerName} orderId={created.orderId || created.id} deliveryCode={created.deliveryCode} /><Link className="button button-primary" href={`/owner/orders/${created.id}`}>View order</Link></div></div></div></AppShell>;
  return <AppShell role="OWNER"><div className="page"><header className="page-header"><div><p className="eyebrow">New order</p><h1>Create an order</h1><p className="subtext">The backend will generate the order ID and delivery code.</p></div></header><section className="panel"><form className="panel-body" onSubmit={form.handleSubmit(values => mutation.mutate(values))}><div className="form-grid"><div className="field"><label htmlFor="customerName">Customer name</label><input className="input" id="customerName" {...form.register("customerName")} />{form.formState.errors.customerName && <small>{form.formState.errors.customerName.message}</small>}</div><div className="field"><label htmlFor="customerPhone">Customer phone</label><input className="input" id="customerPhone" type="tel" {...form.register("customerPhone")} />{form.formState.errors.customerPhone && <small>{form.formState.errors.customerPhone.message}</small>}</div><div className="field field-span"><label htmlFor="orderDetails">Order details</label><textarea className="textarea" id="orderDetails" rows={3} {...form.register("orderDetails")} />{form.formState.errors.orderDetails && <small>{form.formState.errors.orderDetails.message}</small>}</div><div className="field field-span"><label htmlFor="deliveryAddress">Delivery address</label><textarea className="textarea" id="deliveryAddress" rows={3} {...form.register("deliveryAddress")} />{form.formState.errors.deliveryAddress && <small>{form.formState.errors.deliveryAddress.message}</small>}</div><div className="field"><label htmlFor="amount">Amount <span className="muted">(optional)</span></label><input className="input" id="amount" type="number" min="0" step="0.01" placeholder="0.00" {...form.register("amount")} /></div><div className="field"><label htmlFor="assignedRiderId">Assign rider <span className="muted">(optional)</span></label><select className="select" id="assignedRiderId" {...form.register("assignedRiderId")}><option value="">Unassigned</option>{(riders.data || []).map(rider => <option key={rider.id} value={rider.id}>{rider.name}</option>)}</select></div></div>{mutation.isError && <p className="form-error">Unable to create the order. Please try again.</p>}<div className="form-actions"><Link href="/owner/orders" className="button button-secondary">Cancel</Link><button className="button button-primary" disabled={mutation.isPending}>{mutation.isPending ? "Creating..." : "Create order"}</button></div></form></section></div></AppShell>; }
